server:
  port: 0


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
      enabled: true
  jackson:
    time-zone: Asia/Baku
  datasource:
    name: blog_app
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: 123456789
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
  application:
    name: order-service


#jwt:
#  config:
#    secret-key: 3m59OX5h1ZTJsXmQF36qp7URWdFXV7Pz1WOjOmo9McCLWkxLdUVpiSAN8NlbbRXBDCTBqelhXrTWnz1W1WP0aiaPik7z5oGwYLMB1th5aFQoid2Qh7sadgmErUJstUqe
#    expiration-time: 1
file-upload:
  settings:
    upload-folder: d:/orderservicefiles/uploads/
#logging:
#  file:
#    name: d:/blogappfiles/logs/logFile.txt
#    path: d:/blogappfiles/logs/


eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enabled: true
  endpoint:
     health:
        show-details: "ALWAYS"
  endpoints:
    web:
        exposure:
          include: "*"

resilience4j:
  circuitbreaker:
    instances:
      - product:
          registerHealthIndicator: true
          event-consumer-buffer-size: 0
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
          timeout-duration: 3s
          max-attempts: 3
          wait-duration: 5s


